### ISSUE TITLE
Mention in the Readme that you need to install libraqm for proper kerning of text

### ISSUE THREAD

**Issue by dwhit** [thoppe/pixelhouse#26]
I was messing around with some of the examples and I couldn't figure out why my name wasn't kerned properly, until I dug around enough and found out that Pillow requires a package called libraqm to be installed to use the kerning specified by the ttf and otf files. Once I installed it, the weird kerning between the A and V in my name was fixed, as seen below.

Bad Kerning:
![no_kern](https://user-images.githubusercontent.com/2936682/49470606-8a4b7e00-f7d8-11e8-9847-a8e5280670d2.png)

Proper Kerning:
![proper_kerning](https://user-images.githubusercontent.com/2936682/49470614-8f103200-f7d8-11e8-9f74-18b9af27cb34.png)

Relevant package: https://github.com/HOST-Oman/libraqm

If you wanted, you could even add an argument to the pixelhouse text class to turn kerning (or any TTF/OTF font feature on or off)

**Comment by thoppe** [comment]
Oh gross, I didn't even notice that was an issue. Fonts are a complicated piece that I've really only laid the groundwork for. At them moment, I'll see if I can trigger a warning to the user that they should install it for better kerning.

Can I ask how you installed https://github.com/HOST-Oman/libraqm ? It doesn't look like there is anything simple in it w.r.t. a package manager (eg. it's not in Ubuntu's `apt get`). Asking users to install (and build!) another package is a bit much.

**Comment by dwhit** [comment]
Yeah it's a pain the in the butt to install. I just had to follow the instructions from the github page. I use a mac, so I installed the dependencies with homebrew, and then cloned the repo and built from source.

**Comment by thoppe** [comment]
Alright, thanks for the info. I'll add some information in the README that highlights how to achieve better kerning with libraqm.
