### ISSUE TITLE
Overlay a partially-transparent Canvas on-top of another Canvas

### ISSUE THREAD

**Issue by samclane** [thoppe/pixelhouse#38]
I'm trying to composite these two images:

https://imgur.com/a/0RaH9zq

Ideally, the Tree should appear on top of the Grass tile. Following the examples, I made this short piece of code to test this idea:

```
from pixelhouse import Canvas

spr = Canvas().load(r"C:\Users\SawyerPC\PycharmProjects\Discordia\Discordia\Interface\Rendering\Sprites\Terrain\grass_center.png")
spr.show()
with spr.layer() as layer:
    c = Canvas().load(r"C:\Users\SawyerPC\PycharmProjects\Discordia\Discordia\Interface\Rendering\Sprites\Structures\wilds_default.png")  # Tree Sprite
    c.show()
    layer += c
spr.show()
```

I've tried manually calling `Canvas().combine()` with `mode` equal to `blend`, `add`, and `subtract`, all of which don't seem to change the final `Canvas` object at all. Is there an easy way to superimpose one `Canvas` on top of another? Thank you.

**Comment by thoppe** [comment]
First make sure that you're using the latest version of pixelhouse `pip install pixelhouse --upgrade`. Next, note that the overlay function works on _transparent_ pixels. So either you'll have to set them as transparent in Photoshop/GIMP or do it yourself. In this case it's really easy since [you want the black pixels to be transparent](https://stackoverflow.com/questions/52735231/how-to-select-all-non-black-pixels-in-a-numpy-array):


``` python
import pixelhouse as ph
import numpy as np

grass = ph.load('grass.png')
tree  = ph.load('tree.png')

black_pixels = np.all(tree.img == [0,0,0,0], axis=-1)

transparent_tree = tree.copy()
transparent_tree[~black_pixels, 3] = 255  # The last channel is the alpha channel

overlay = grass.copy().combine(transparent_tree)
canvas = ph.hstack([grass, tree, overlay])

canvas.show()

canvas += ph.transform.scale(4.0)
canvas.save('combo.png')
```


![combo](https://user-images.githubusercontent.com/2707106/57627928-f8098c00-7566-11e9-9211-0d86ae2dca71.png)

**Comment by thoppe** [comment]
Thanks for leaving a good issue! Every question exposes good things missing from the library -- in this one, I realized there isn't a good way to select all "black" pixels, or select by threshold. I might try to add that in the future!

**Comment by samclane** [comment]
I don't know why it's uploading with black pixels. It's a png, the alpha values for transparency seem to be loading incorrectly, both in imgur and pixelhouse/cv2. I'll upload the png file directly. See how it works with this.
![tree_single](https://user-images.githubusercontent.com/5761099/57634515-af4fd400-7562-11e9-83b3-6607848353c2.png)

(github seems to get the transparency correctly)

**Comment by thoppe** [comment]
Ah! Thanks for uploading the image. It looks like `cv2` seems to ignore the alpha channel when loading from a file. I think there is an easy fix for this.

**Comment by thoppe** [comment]
This now works much simpler! Check this out:

```
import pixelhouse as ph

grass = ph.load('grass.png')
grass += ph.load('tests/tree.png')

grass.show()
```

![output](https://user-images.githubusercontent.com/2707106/57641676-986da980-7583-11e9-9093-05239050ccbd.png)

**Comment by thoppe** [comment]
For this to work, update to 0.4.9, `pip install pixelhouse -U`
