### ISSUE TITLE
Allow installation with other OpenCV distributions

### ISSUE THREAD

**Issue by samclane** [thoppe/pixelhouse#41]
I'm in an odd use-case where I'm working with Python 3.7 on a Raspberry Pi. As 3.7 isn't officially available, I had to just through some hoops to get it running. [I also compiled OpenCV from source](https://www.pyimagesearch.com/2018/09/26/install-opencv-4-on-your-raspberry-pi/). However, I see that `pixelhouse` uses the prebuilt binaries from `opencv-python`. Normally, python can install pre-built `opencv-python` wheels from https://www.piwheels.org/, but these are only for the officially supported versions (2.7 and 3.5). 

From what I've read, all the different wrappers from Python to OpenCV use the same namespace, `cv2`. This means that (ideally) shouldn't be any changes to the code, only `setup.py` and `requirements.txt` perhaps. I'm just not sure how `setuptools` would handle an "optional" requirement. However, I'm not sure how to setup `pixelhouse` without this change.

Thanks.

**Comment by thoppe** [comment]
Hi @samclane! I'm interested in what you're using pixelhouse for on a Pi, please share the project!

For this one-off use case, I recommend installing pixelhouse directly from source. This way you can edit the setup.py directly to exclude the default opencv repo. Note that the `requirements.txt` simply installs what's in the setup.py _and_ a few tools needed for development like code linting and testing.

    git clone https://github.com/thoppe/pixelhouse
    cd pixelhouse
    # edit setup.py as needed
    pip install -e .   # Install locally

Either way, pixelhouse looks to call `import cv2` at some point. If you've installed something in that namespace it should work!

**Comment by samclane** [comment]
Thanks for the info on how to manually install. I've only had to do it a couple of times and it always weirds me out. But I'll certainly give it a go today.

I'm working on a grid-based video game called [Discordia](https://github.com/samclane/Discordia). It's emulating the Multi-User Dungeon (or MUD) genre. It runs on top of the Discord voice/text chat platform (and offloads all the networking) using [discord.py](https://github.com/Rapptz/discord.py).

Since MUDs are slow-paced, it doesn't need real-time graphics. Players can request a screenshot of their surroundings with a text command. PixelHouse makes it easy to composite `Canvas` objects together while also keeping them separate, so I can render views independent of the main map image. It's also surprising how many Python game engines don't support exporting image files or do it very poorly. 

I also want to add animations and gifs eventually, which I think `ph` should be able to do just fine.

**Comment by thoppe** [comment]
This is great! Let me know what I do can to make sure `ph` is helping you. If you like, when you finish I'll put a link on the main readme to your site.

**Comment by samclane** [comment]
Thanks! I'll keep opening issues for any bugs I come across (not niche like this one). And thanks for the offer to link to my repo!
