### ISSUE TITLE
 Getting the data and the model needs a little help

### ISSUE THREAD

**Issue by zhanghongyong123456** [thoppe/pixelhouse#43]
I am a student in the School of Film and I am very interested in this project. I want to get the model and data and study it by myself. Do you have it and can you share with me
https://github.com/rsomani95/shot-type-classifier

I want to get the data set and model of this project. Do you have it? I saw the link that the author of the project has cancelled

Thank you very much and look forward to your reply

**Comment by thoppe** [comment]
Hi @zhanghongyong123456 . You'll have to [contact the author directly](https://github.com/rsomani95/shot-type-classifier/issues/5), they own the rights to the model. They have provided an email address to contact them, I'd start there!

**Comment by zhanghongyong123456** [comment]
> Hi @zhanghongyong123456 . You'll have to [contact the author directly](https://github.com/rsomani95/shot-type-classifier/issues/5), they own the rights to the model. They have provided an email address to contact them, I'd start there!

Yes, I did, but there was no response, and I'm not sure if I got a hold of him，That's why I chose to ask if you had storage
